### PR TITLE
Pull request to fix issue #1

### PR DESCRIPTION
**Pull request by hjeldin**

### CODE REVIEW

**Comment by vkhandus** [comment]
You removed C99 compatibility just to use 'auto' keyword? This isn't good. Many embedded dev still use old toolchains without C++11 support.

**Comment by hjeldin** [comment]
Actually I didn't, there's no reference to 'auto' in my committed code.

**Comment by vkhandus** [comment]
Yes, I see now. Sorry. 'auto' was added by author about a year ago.

**Comment by zk4** [comment]
already merged,thanks~

**Pull request closed without merging**
